FROM node:latest

LABEL name="aa-wallet"
ENV APP_DIR=/app

WORKDIR APP_DIR

ADD package*.json ./
ADD . .

RUN echo $(ls)

RUN npm install

CMD ["npm", "run", "bundler", "--unsafe"]

EXPOSE 3000