pipeline {
    agent any

    // environment {}

    stages{
        stage("Lagacy Remove") {
        steps{
            script {
            try {
                sh "docker rmi -f bundler-server:latest"
            } catch (err) {
                echo "The image of bundler-server is not defined"
            }
            }
            script {
            try {
                sh "docker rm -f bundler-server"
            } catch (err) {
                echo "bundler-server is not defined"
            }
            }
        }
        }
        stage("Build") {
        steps{
            sh "docker buildx build -t bundler-server ./bundler-server"
        }
        }
        stage("RUN") {
        steps {
            sh """docker run -d \
                    --name bundler-server \
                    -p 3000:3000 \
                    bundler-server:latest"""
        }
        }
    }
}